const ENTITIES = {
    PRODUCT: 'products',
    STOCK_LOCATION: 'stock_location',
    PRODUCT_STOCK: 'product_stock'
}

const NAME_ENTITIES = {
    PRODUCT: 'Produto',
    STOCK_LOCATION: 'Local de Estoque',
    PRODUCT_STOCK: 'Estoque do Produto'
}

const SHORT_MESSAGES = {
    NOT_FOUND: 'Não foi localizado',
    CREATE_SUCESS: 'Criado com sucesso!',
    EDIT_SUCESS: 'Editado com sucesso!',
    DELETE_SUCESS: 'Removido com sucesso!',
}

const MESSAGES = {
    PRODUCT_NOT_FOUND: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    STOCK_LOCATION_NOT_FOUND: NAME_ENTITIES.STOCK_LOCATION.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    PRODUCT_STOCK_NOT_FOUND: NAME_ENTITIES.PRODUCT_STOCK.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    PRODUCT_CREATE_SUCESS: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.CREATE_SUCESS),
    STOCK_LOCATION_CREATE_SUCESS: NAME_ENTITIES.STOCK_LOCATION.concat(' ', SHORT_MESSAGES.CREATE_SUCESS),
    PRODUCT_STOCK_CREATE_SUCESS: NAME_ENTITIES.PRODUCT_STOCK.concat(' ', SHORT_MESSAGES.CREATE_SUCESS),
    PRODUCT_EDIT_SUCESS: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.EDIT_SUCESS),
    STOCK_LOCATION_EDIT_SUCESS: NAME_ENTITIES.STOCK_LOCATION.concat(' ', SHORT_MESSAGES.EDIT_SUCESS),
    PRODUCT_STOCK_EDIT_SUCESS: NAME_ENTITIES.PRODUCT_STOCK.concat(' ', SHORT_MESSAGES.EDIT_SUCESS),
    PRODUCT_DELETE_SUCESS: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    STOCK_LOCATION_DELETE_SUCESS: NAME_ENTITIES.STOCK_LOCATION.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    PRODUCT_STOCK_DELETE_SUCESS: NAME_ENTITIES.PRODUCT_STOCK.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    VALIDATION_ERROR: 'Erro de validação:' 
}

const RETURN_CODES = {
    INTERNAL_SERVER_ERROR: 500,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    CREATED: 201,
};

module.exports = {
    ENTITIES,
    NAME_ENTITIES,
    MESSAGES,
    RETURN_CODES
}